# Generated by Django 4.0.3 on 2022-04-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('profId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('profName', models.CharField(max_length=100)),
                ('deptName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=100)),
                ('extraInfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100)),
                ('projectDesc', models.CharField(max_length=100)),
                ('projectField', models.CharField(max_length=100)),
                ('projectStatus', models.CharField(max_length=100)),
                ('numberOfCurrentApplicants', models.IntegerField()),
                ('profId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.professor')),
            ],
        ),
    ]
