# Generated by Django 4.0.4 on 2022-04-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='deptName',
            new_name='deptId',
        ),
    ]
