# Generated by Django 4.0.4 on 2022-04-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_department_rename_deptname_professor_deptid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='professor',
            name='ResearchInterest',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='maxNumberOfApplicants',
            field=models.IntegerField(default=1000),
        ),
    ]
