# Generated by Django 4.0.4 on 2022-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_project_profid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDesc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectField',
            field=models.CharField(max_length=500),
        ),
    ]
