# Generated by Django 4.0.4 on 2022-04-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_project_projectdesc_alter_project_projectfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=200),
        ),
    ]
